### ISSUE TITLE
Market orde doesn't work?

### ISSUE THREAD

**Issue by john8988** [alienbrett/PyAlly#52]
HELP! First time using this and tried it with market order and had the following error

The code:  (just use as the example in your document): allyO is the ally object that has been verified to work for many other functions like balances, quote and timesales

 o = ally.Order.Order(buysell = 'buy', symbol='AAPL', price = ally.Order.Market(), time='day', qty=1)
allyO.submit(o,preview=False)

The error message:

    allyO.submit(o,preview=False)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ally\Order\Submit.py", line 159, in submit
    block               = block
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ally\Api.py", line 206, in __init__
    super().__init__(auth,**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ally\Api.py", line 171, in __init__
    send_params, send_data = self.req_body (**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ally\Order\Submit.py", line 92, in req_body
    data = self._order.fixml
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ally\Order\order.py", line 190, in fixml
    d.update(self.pricing.fixml)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ally\Order\classes.py", line 99, in fixml
    return self._tag
AttributeError: 'Market' object has no attribute '_tag'

**Comment by john8988** [comment]
Turns out it has errors on other order types like limit too. Some gross usage error?

>>> o1 = ally.Order.Order(buysell = 'buy', symbol='RMD', price=ally.Order.Limit(173), time='day', qty=1)
>>> print(o1)
(OType.Order) Side.Buy 1 units of "RMD" TimeInForce.Day, Limit $173.000
>>> a.submit(o1, preview=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ally\Order\Submit.py", line 159, in submit
    block               = block
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ally\Api.py", line 206, in __init__
    super().__init__(auth,**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ally\Api.py", line 171, in __init__
    send_params, send_data = self.req_body (**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ally\Order\Submit.py", line 92, in req_body
    data = self._order.fixml
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ally\Order\order.py", line 190, in fixml
    d.update(self.pricing.fixml)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ally\Order\classes.py", line 99, in fixml
    return self._tag
AttributeError: 'Limit' object has no attribute '_tag'
