### ISSUE TITLE
Problem with order placing

### ISSUE THREAD

**Issue by ortamir** [alienbrett/PyAlly#55]
Hi,

I'm trying to place an order using this API.

Here is the code I'm running:

    account1 = ally.Ally(params1)
    order = ally.Order.Order(
        buysell='buy',
        symbol='f',  # case insensitive
        price=ally.Order.Market(),
        time='day',
        qty=2
    )
    order_id = account1.submit(order, preview=False)

I'm getting this traceback:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Owner/PycharmProjects/stacky/ally_api.py", line 128, in <module>
    order_id = account1.submit(order, preview=False)
  File "C:\Users\Owner\PycharmProjects\stacky\venv\lib\site-packages\ally\Order\Submit.py", line 154, in submit
    result = Submission(
  File "C:\Users\Owner\PycharmProjects\stacky\venv\lib\site-packages\ally\Api.py", line 206, in __init__
    super().__init__(auth,**kwargs)
  File "C:\Users\Owner\PycharmProjects\stacky\venv\lib\site-packages\ally\Api.py", line 171, in __init__
    send_params, send_data = self.req_body (**kwargs)
  File "C:\Users\Owner\PycharmProjects\stacky\venv\lib\site-packages\ally\Order\Submit.py", line 92, in req_body
    data = self._order.fixml
  File "C:\Users\Owner\PycharmProjects\stacky\venv\lib\site-packages\ally\Order\order.py", line 190, in fixml
    d.update(self.pricing.fixml)
  File "C:\Users\Owner\PycharmProjects\stacky\venv\lib\site-packages\ally\Order\classes.py", line 99, in fixml
    return self._tag
AttributeError: 'Market' object has no attribute '_tag'

**Comment by alienbrett** [comment]
Which version are you using- this should have been fixed in the latest V1.1.0. Please print the output of `pip3 show pyally`

**Comment by ortamir** [comment]
Seems I used V1.0.6, updated to V1.1.0 and it works. Thanks a lot!

Best,

Orr
